[package]
name = "vindinium"
version = "0.0.1"
authors = ["jxv https://github.com/jxv/vindinium-starter-rust"]

[dependencies]
hyper = "0.9.9"
url = "1.1.1"
rustc-serialize = "0.3.19"
rand = "0.3.14"
term = "0.4.4"
